#!/bin/sh
### RunAg10
#PBS -N short_Ag10
### Output files
#PBS -o short_Ag10.stdout
#PBS -e short_Ag10.stderr
### Queue name
#PBS -q default
### Number of nodes
#PBS -l nodes=1:ppn=32
#PBS -V

module load openmpi_eth
module load intel2013

cd $PBS_O_WORKDIR

mpirun -np 32 /home/sebas/lammps-12Dec18/src/lmp_mpi < ZrCuAg.lmp.in
