#!/bin/sh
### RunAg0
#PBS -N RunAg0
### Output files
#PBS -o RunAg0.stdout
#PBS -e RunAg0.stderr
### Queue name
#PBS -q default
### Number of nodes
#PBS -l nodes=1:ppn=32
#PBS -V

module load openmpi_eth
module load intel2013

cd $PBS_O_WORKDIR

mpirun -np 32 /home/sebas/lammps-12Dec18/src/lmp_mpi < ZrCuAg.lmp.in
